### ISSUE TITLE
The sudo description isn't accurate

### ISSUE THREAD

**Issue by Coder-256** [idank/explainshell#123]
[When you enter `sudo`](http://explainshell.com/explain?cmd=sudo), you get a slightly inaccurate description:

`execute a command as another user`

Maybe "execute a command as the *superuser*" or something similar would be better?

**Comment by idank** [comment]
I didn't make that up.. It's taken from the synopsis of the man page http://manpages.ubuntu.com/manpages/precise/en/man8/sudo.8.html

Good luck trying to get that to change :)
