### ISSUE TITLE
Recognize shell builtin `:` (synonymous with `true`)

### ISSUE THREAD

**Issue by zrajm** [idank/explainshell#124]
`:` is synonymous with `true` in at least `bash`, `dash` (Debian Almquist Shell) and `zsh` – except in that `:` is a shell builtin available in all those shells, and `true` usually executes `/bin/true` (except under `zsh` where `true` and `:` are both builtins).

**Comment by ScoreUnder** [comment]
It looks like they're even more synonymous than that. `true` is a builtin in bash (4.3.39(1)), dash (0.5.8), mksh (50.f), busybox sh (1.23.2 with all applets), posh (0.12.4) and zsh (5.0.8) -- i.e. all shells I can think of to test them with.

I have to vouch for this, I use `:` a lot in scripts variously for the purpose of soaking up a parameter expansion (like ${1?blah}), returning true, or giving a dummy command name somewhere.
