### ISSUE TITLE
name resolve order = bcast host

### ISSUE THREAD

**Issue by Smereczniak** [idank/explainshell#127]
https://www.liberiangeek.net/2012/03/how-to-fix-failed-to-retrieve-share-list-from-server-in-ubuntu-12-04-11-10-when-file-sharing-with-windows/

The above link fixed new install of Linux Mint 17.1 64 bit networking issue. Could not resolve shared computer in Windows 7 and 8.1 until I applied the above command line. 
Would like to know how it works.

**Comment by idank** [comment]
That seems to be about a configuration file and not a command line?

This might help though: http://manpages.ubuntu.com/manpages/vivid/en/man5/smb.conf.5.html
