### ISSUE TITLE
Please support HTTPS on explainshell.com

### ISSUE THREAD

**Issue by FiloSottile** [idank/explainshell#135]
Past the argument for global TLS (which is sorely needed to stop ad and attack vectors injection), it's unpleasant to send one's command line in plain text.

As a quick, simple and free solution you can just turn on CloudFlare Flexible SSL. (Disclosure: I work for CF.) To protect also the segment from CF servers to yours you can get a free certificate issued by us, but first you should at least secure the last mile.

Let me know if I can help with that.

**Comment by idank** [comment]
You're the first to ask, but I'm fine with adding it if it's easy. Is there a guide somewhere?

**Comment by FiloSottile** [comment]
You can just sign up at cloudflare.com, and turn on Flexible SSL in the control panel. That should be it, but let me know if you have trouble.

**Comment by Semyazz** [comment]
Sorry, but you do it wrong if you send sensitive command line to a public website ;-) Run your local copy instead.

**Comment by Arthur2e5** [comment]
The incoming [Let's Encrypt](https://letsencrypt.org) CA provides tools to get and deploy a certificate easily. According to the news it has just got cross-signed so it should be trusted by most browsers.

**Comment by rugk** [comment]
[Let's Encrypt](https://letsencrypt.org/) is now in public beta and this therefore HTTPS can be easily added here. Much better than Cloudflare BTW... :smile:

**Comment by arahayrabedian** [comment]
+1 on let's encrypt, enabled HTTPS on two of my domains just a few days
ago, took under an hour and is so automated I didn't even need open their
website, just github (account creation is done with their tool, as is
domain verification). Only drawback is 90 day validity.

**Comment by rugk** [comment]
Any news here?

**Comment by idank** [comment]
No. Can anyone recommend a recent guide on setting up letsencrypt with nginx?

**Comment by rugk** [comment]
It really depends on what you want to do.

I'd recommend first reading https://letsencrypt.org/getting-started/ and then choosing a [client](https://letsencrypt.org/docs/client-options/). If you're fine with the official client you can use it and AFAIK it has some integration for nginx.

If you'd rather want a small, hackable/customizable script then you can use this guide: https://scotthelme.co.uk/setting-up-le/

**Comment by idank** [comment]
Ok, went over https://letsencrypt.org/getting-started/. It doesn't look trivial and I haven't done this before so I'll have to go through the docs. It's probably a good idea to update the host while we're at it, it's running 12.04.

I don't have time for this adventure now, hopefully will in the near future.

**Comment by rugk** [comment]
In case you already configured HTTPS once it is easy. If not, you'll learn it quickly.

**Comment by cuongnv23** [comment]
Hi @idank,
I would recommend `certbot`, it has detail and easy steps to follow https://certbot.eff.org/#ubuntutrusty-nginx

**Comment by idank** [comment]
Finally got around to doing this. Let me know if something isn't setup right.
