### ISSUE TITLE
explainshell presumes 'make' is GNU make

### ISSUE THREAD

**Issue by grimreaper** [idank/explainshell#145]
when it is quite often bmake or nmake
and thus gets the argument parsing entirely wrong

**Comment by idank** [comment]
The man pages were scraped from Ubuntu, so it presumes whatever ships with Ubuntu, which is GNU make. I don't manually add single man pages anymore, perhaps in the future I would scrape some BSD archive, but I don't have the bandwidth to do it t these days.
