### ISSUE TITLE
‘Assignment’ / equals-mark flags?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [idank/explainshell#152]
So, the last argument of this command fails to parse:

    aria2c --continue --split=16 --max-connection-per-server=16 --max-concurrent-downloads=20 \
       http://tug.org/cgi-bin/mactex-download/MacTeX.pkg \
       --checksum=md5=bf579a512d31253d828591fdb3644dca

Are `--foo=bar` arguments supported? If so, is this just a strange case, due to a second equals-mark? =)

**Comment by idank** [comment]
Parsing it is working fine. It seems the --checksum isn't on the list of arguments for this binary: http://explainshell.com/explain/1/aria2c so its format in the man page wasn't caught by explainshell.
