### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by avindra** [idank/explainshell#155]
I love this site - and would love to see something like a dark theme to make it easier on the eyes.

Then allow users to configure what theme they want to use (cached in localStorage or otherwise to make things simple).

I am a web developer so I could take a stab at it, but would like to hear your thoughts first.

**Comment by idank** [comment]
Sure, go for it. Would a cookie make more sense?

**Comment by avindra** [comment]
`localStorage` is supported on all major browsers (including ie8)

http://caniuse.com/#search=localstorage

It allows more storage (up to 5MB of data) and has a nicer API. Also, `localStorage` has no expiration date and can only be cleared programmatically... which is a nice way to implement user settings without standing up infrastructure on your side for it.

I'll put something together and send a PR!

**Comment by karltaylor** [comment]
How far did you get with this? Would love to help out

**Comment by avindra** [comment]
@karltaylor : You can take a stab at it, I haven't touched it.

I had trouble standing up a local dev copy of the python environment, I'm more of a node guy.

**Comment by stoivo** [comment]
Hello @avindra and @karltaylor 

I created a docker file so all you need to get started is to follow this guild https://github.com/idank/explainshell/tree/fe844caa79564a3101d9cb27c0322f1c9bd6e0d6#start-up-a-local-web-server-with-docker

I would love to see a dark theme.

**Comment by avindra** [comment]
@stoivo  Great work on the docker stuff. Much less painful than working with Vagrant! :+1: :+1: 

I opened PR #171 to start us off. Do you by chance have methods for importing more data than just the ones for `grep`? Would be helpful for testing more robustly locally.

**Comment by avindra** [comment]
To answer my own question, running `PYTHONPATH=. python explainshell/manager.py --log info /usr/share/man/man1/*` in the container works

**Comment by stoivo** [comment]
Sweet, as you said `PYTHONPATH=. python explainshell/manager.py --log info /usr/share/man/man1/*` will update the database. If  you would like something special like rsync,  ncdu, git, etc I would install it with apt-get and then import the files again.

I am looking forward to this.

**Comment by anestv** [comment]
I'm preparing something for this

**Comment by stoivo** [comment]
Awesome

**Comment by jtojnar** [comment]
This can be closed.

**Comment by avindra** [comment]
nice work @anestv .

thank you!
