### ISSUE TITLE
If statement

### ISSUE THREAD

**Issue by vqw** [idank/explainshell#157]
Hi guys,

Recently I have pasted this command:
**if ps ax | grep -v grep | grep "./virtenv/shipdatabaseVirtenv/bin/uwsgi" > /dev/null**

Which gave me **unexpected EOF**.
Right now anytime from any browser from different IP's when I ask explainshell for:
**if** it gives me **unexpected EOF**.

Cheers

**Comment by idank** [comment]
The command isn't complete. Try running it in bash, you'll see a similar error.

This should work:

if ps ax | grep -v grep | grep "./virtenv/shipdatabaseVirtenv/bin/uwsgi" > /dev/null; then a; fi
