### ISSUE TITLE
how the data in dump/explainshell/ was generated?

### ISSUE THREAD

**Issue by benquike** [idank/explainshell#161]
As the title says

**Comment by idank** [comment]
The classifier table? I manually went over man pages and labeled the paragraphs. Then used that as the training set for the classifier.

**Comment by benquike** [comment]
I am not sure I am correct or not.
Do you use the code in explainshell/manager.py to generate the classifier table?

**Comment by idank** [comment]
Can you give me some background on what you're trying to do? It'll be easier for me to help you.

**Comment by benquike** [comment]
Simply put, I want to build a database of the program options/arguments by parsing the man pages. because I want to use this information to do some other tasks.

**Comment by idank** [comment]
Did you have trouble following the instructions in the readme? It should have everything you need.

**Comment by benquike** [comment]
Following your README, I can run explain shell locally.

But I want to build the classifier myself.

**Comment by benquike** [comment]
I think I got your idea.
Thanks very much

**Comment by idank** [comment]
It should get you to a point where you can feed it a man page and it will insert it into the database. Let me know if you run into issues.

**Comment by benquike** [comment]
One more thing, can you give me the training corpus?
