### ISSUE TITLE
sed -e '1,2d' -e $(($(wc -l <file1)-3+1)),\$d x > file2

### ISSUE THREAD

**Issue by gitryarlagadda** [idank/explainshell#175]
This command did not parsed/Explained
sed -e '1,2d' -e $(($(wc -l <x)-3+1)),\$d x > x2

**Comment by idank** [comment]
Unfortunately arithmetic expressions aren't supported and I don't have the bandwidth to add it :(.  Closing as it's a dupe of #109.
