### ISSUE TITLE
Tutorial: how to add ExplainShell to omnibox

### ISSUE THREAD

**Issue by Pablohn26** [idank/explainshell#180]
I like omnibox search engines, that is why I left here a quick tutorial to add ExplainShell to Google Chrome/Chromium omnibox. With this feature, you would be able to search a command in this way:

![selection_187](https://cloud.githubusercontent.com/assets/1228418/24632698/6516374a-18c5-11e7-81a5-c6b2b59af3c7.png)

and once you press enter you will go to this URL:

![selection_165](https://cloud.githubusercontent.com/assets/1228418/24632739/985130c4-18c5-11e7-9293-be31d1a2c305.png)

It is easy, quick and its set up is just 2 minutes 

To enable this, secondary click on omnibox and click on _Edit search engines_ . Then go below to add a new search engine with following information
* First field (customizable): name of the search engine
* Second field (customizable): word to call that search engine
* Third field (not customizable): `http://explainshell.com/explain?cmd=%s`

![selection_164](https://cloud.githubusercontent.com/assets/1228418/24633012/aeecf132-18c6-11e7-8bbf-f97f59803dfb.png)

Sorry if this is not a good place for this information. Feel free to copy/edit/share this information or add a link to it on readme If it has a good feedback.

Thanks for this project :1st_place_medal:

**Comment by idank** [comment]
Thanks! I'll make sure this ends up in the wiki.

**Comment by stoivo** [comment]
https://github.com/idank/explainshell/wiki/Tutorial:-How-to-add-ExplainShell-to-omnibox
Does this look good?

Should be we add a link to the wiki from the index page?
![2017-05-05_09-37-56_explainshell com - match command-line arguments to their help text](https://cloud.githubusercontent.com/assets/3492040/25737200/b9a9233e-3176-11e7-8bdd-012c8519df2c.png)

**Comment by idank** [comment]
Looks good, thank you! The third screenshot you added is leaking all your search engines. :)

**Comment by stoivo** [comment]
Screenshots are from @Pablohn26, he said we could use them.

Add a link on the main page?
