### ISSUE TITLE
improve the Dockerfile

### ISSUE THREAD

**Issue by k3ck3c** [idank/explainshell#181]
Hello

it would be more compliant with the Dockerfile best practices 
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
to do 

FROM python:2.7

MAINTAINER Simon Toivo Telhaug <simon.toivo@gmail.com>

RUN apt-get update && apt-get install man-db -y

ADD ./requirements.txt /tmp/requirements.txt

RUN pip install --upgrade pip \
&& python --version \
&& pip install -r /tmp/requirements.txt

ADD ./ /opt/webapp/
WORKDIR /opt/webapp
EXPOSE 5000

CMD ["make", "serve"]

**Comment by idank** [comment]
Can you turn this into a pull request? Thanks!

**Comment by idank** [comment]
merged, thanks!
