### ISSUE TITLE
Want to install locally. I'm getting the following error

### ISSUE THREAD

**Issue by JL01152** [idank/explainshell#187]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iMOVIG/nltk/

my python version is Python 2.7.12

**Comment by idank** [comment]
Can you paste the whole thing starting from the command you ran? Thanks.

**Comment by JL01152** [comment]
dirtynix@dirtynix:~/dirty repos/command glossary$ pip install -r requirements.txt 
Collecting Flask==0.12 (from -r requirements.txt (line 1))
  Using cached Flask-0.12-py2.py3-none-any.whl
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 2))
  Using cached MarkupSafe-1.0.tar.gz
Collecting nltk==2.0.5 (from -r requirements.txt (line 3))
  Using cached nltk-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpFx1ph0
    Now working in /tmp/tmpFx1ph0/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-iMOVIG/nltk
    Traceback (most recent call last):
      File "setup.py", line 37, in <module>
        exec(open(init_path).read(), d)
      File "<string>", line 8, in <module>
      File "/tmp/tmpFx1ph0/distribute-0.6.21/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/tmpFx1ph0/distribute-0.6.21/setuptools/extension.py", line 2, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/tmpFx1ph0/distribute-0.6.21/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/tmp/tmpFx1ph0/distribute-0.6.21/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/tmpFx1ph0/distribute-0.6.21/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/tmpFx1ph0/distribute-0.6.21/pkg_resources.py", line 2729, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpFx1ph0/distribute-0.6.21/pkg_resources.py", line 700, in subscribe
        callback(dist)
      File "/tmp/tmpFx1ph0/distribute-0.6.21/pkg_resources.py", line 2729, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpFx1ph0/distribute-0.6.21/pkg_resources.py", line 2229, in activate
        self.insert_on(path)
      File "/tmp/tmpFx1ph0/distribute-0.6.21/pkg_resources.py", line 2330, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
    /tmp/pip-build-iMOVIG/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iMOVIG/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-iMOVIG/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-iMOVIG/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/pip-build-iMOVIG/nltk/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iMOVIG/nltk/


I tried searching for a similar issue and found a closed issue however I was unable to fix the problem. I must say it was beyond my scope. Hence the need for your tool. lol

**Comment by idank** [comment]
Honestly not sure what it wants. What version of python are you running? Is this inside a virtualenv? I'll try to follow your steps and see if I can get it to work.

**Comment by JL01152** [comment]
Ubuntu 16.04 lts native installation. Python 2.7


________________________________

**Comment by stoivo** [comment]
Can you use docker?

**Comment by JL01152** [comment]
Sorry, I don't know what Docker is. Let me do some searching and find out more about it and I'll get back to you.

**Comment by akshay2000** [comment]
@JL01152 Upgrading setuptools using `pip install -U setuptools` fixed it for me. Does it work for you? Were you able to get the set up done?

**Comment by JL01152** [comment]
@akshay2000 That just fixed it for me. Thank you. I had gotten caught up with other things and never got around to following up on this. Had it not been for you I still would've been breaking my head with it. :)

**Comment by rohit-nair** [comment]
@dubiouscript Do you remember what was the edit to `requirements.txt` that fixed the issue for you? I'm getting the error but the link you have to xhaa123 doesn't resolve.

**Comment by rohit-nair** [comment]
For anyone stumbling here with the error, here's what worked for me after having to do a bit of head banging.

1. Latest Setuptools version (48.0) fails, so installed an older version in a conda python 2.7 env
`pip install -Iv setuptools==32.0.0`

2. `nltk` refuses to install as mentioned by OP. So for that, I followed these steps:
  - `wget https://pypi.python.org/packages/50/9e/39418026bf8013bbc2852c7aec3fb21e4339f6cd694934496d67a19b53b8/nltk-2.0.5.tar.gz#md5=c3f77cc1bf6c6bc85db6629b7d23c3b9`
  - `tar -xzf nltk-2.0.5.tar.gz`
  - `Change DEFAULT_URL from http to https in nltk-2.0.5/distribute_setup.py`
  - `pip install ./nltk-2.0.5`

This should get anyone facing this issue up and running.

**Comment by idank** [comment]
Ugh, sorry about that. I'll see if the dependencies can be updated to make this less painful.

**Comment by dubiouscript** [comment]
ftr what i have @requirements.txt 
```patch
diff -u explainshell/requirements.txt.old explainshell/requirements.txt 
--- explainshell/requirements.txt.old	2018-12-02 16:06:25.921559578 +0000
+++ explainshell/requirements.txt	2018-12-02 16:07:16.125185517 +0000
@@ -1,6 +1,6 @@
-Flask==0.12
+Flask==0.12.2
 MarkupSafe==1.0
-nltk==2.0.5
-nose==1.3.0
-pymongo==2.6
+nltk==3.2.5
+nose==1.3.7
+pymongo==3.6.0
 bashlex==0.12
```
