### ISSUE TITLE
Add additional parsers e.g. docker

### ISSUE THREAD

**Issue by davidhyman** [idank/explainshell#193]
_Feature suggestion_
Add additional parsers for popular tools, and thus provide support for explaining their commands too.
e.g. docker engine (https://docs.docker.com/engine/reference/commandline/run/#options)
an example from docs: `docker run --device=/dev/sda:/dev/xvdc:rw --rm -it ubuntu fdisk  /dev/xvdc`

---
This is really a question of scope - is explainshell strictly limited to man pages? Additionally there are other shorthands used e.g. ubuntu's `ll -> ls -l` that have no representation in manpages. I'm not aware of anything else providing the wolfram-alpha of command line incantations - perhaps explainshell could provide all of the above?

**Comment by stoivo** [comment]
hm, if I understand you correctly you would like to start the docker container locally import all of the local man pages. This way you will have all the man pages you have locally. Is this correct?

For finding the commands which an alias users I use `type` 
```
$ type ll
ll is aliased to `ls -lh'
```
I believe that should not be a part of explain shell

**Comment by idank** [comment]
The definition of a man page doesn't matter, the format does. It's what allows the tool to find the information it needs. I believe docker has a "man page" somewhere though.

Since aliases are defined by local configuration, I think putting even the popular ones will be confusing.

**Comment by davidhyman** [comment]
@stoivo - yes just import docker manpages (or indeed other programs/tools/utils/commands)

I'll try and explain my reasoning for what sounds like expanding the scope; this is all I have so if it's not convincing, so be it:

on Aliases:
>"aliases are defined by local configuration"

yes but some of them are defined by default, especially on ubuntu. My opinion on this would be that they should be included. Whether it is confusing is a matter of ui (e.g. could just behave in a similar way to wikipedia:
> `ls` (from the alias `ll`)

on extra commands in general:
A primary use case for explain shell (rather than 'explain manpages') is "I have this command I was given/found and want to understand what it does". As such, I don't think, as a user, that I am concerned whether said command is documented on official manpages or not.

Every command phrase (and custom user defined aliase) in the world of course would be impossible to include. I suggest that reaching any % of the additional popular phrases, such as those defined on sites such as StackOverflow and in common distributions, must be more useful than not doing so.

**Comment by stoivo** [comment]
1. Shit load of work to maintain. 
2. If two distros have the same alias for two different commands. We will show incorrect information to one of them, which I think is worse than not covering aliases.

**Comment by idank** [comment]
I think there is room to show distro-sepcific aliases (and man pages too!) because like you said some are pretty ubiquitous. As the saying goes, pull requests welcome. :)
