### ISSUE TITLE
If statements return parsing error every time.

### ISSUE THREAD

**Issue by Guy922** [idank/explainshell#216]
I inserted
if [ -n $X ];
And since then every if statement returns the following (even when inserting other if statements):
<img width="708" alt="screen shot 2018-08-11 at 11 14 04" src="https://user-images.githubusercontent.com/25392426/43989775-1134363a-9d59-11e8-8f71-80296f212cab.png">

**Comment by idank** [comment]
This is an incomplete line, try this: `if [ -n $x ]; then echo a; fi`

https://explainshell.com/explain?cmd=if+%5B+-n+%24x+%5D%3B+then+echo+a%3B+fi
