### ISSUE TITLE
better enviroment for hacking explainshell 

### ISSUE THREAD

**Issue by dubiouscript** [idank/explainshell#223]
perhaps something like 
 https://github.com/uniphil/nix-for-devs/#python 
or 
`nix-shell -p mongodb mongodb-tools man-db certbot uwsgi python2Full python27Packages.supervisor ... `
could provide a better alternative environment to [/misc/setup.bash](https://github.com/idank/explainshell/blob/master/misc/setup.bash )
> TODO(idank): test this on a clean machine

with out the need for a 'clean machine'
also having a shell.nix enviroment would provide an alternative to docker

**Comment by idank** [comment]
I'm not against including other ways to setup a local environment to run explainshell. Currently there's setup.bash and also a Dockerfile. You can also use virtualenv but that only deals with the python envrionment.

I personally don't use nix. If you want to send a pull request, please go ahead.
