### ISSUE TITLE
On resizing browser window the lines pointing the command get cut off

### ISSUE THREAD

**Issue by rumaan** [idank/explainshell#225]
Enter the command and hit explain and resize the window.
<br><i>Tested on Chome and Safari </i>

This has to do with the Responsiveness of the website 👍 

![screenshot 2019-01-24 at 8 02 44 pm](https://user-images.githubusercontent.com/18492868/51684861-0ca33200-2013-11e9-9a8e-cf1fd06e7393.png)

**Comment by idank** [comment]
Yes, sadly the site has a minimum width and the boxes with the arguments text can't shrink lower than that. Unfortunately this isn't easy to fix.
