### ISSUE TITLE
Flashing seen when using dark theme.

### ISSUE THREAD

**Issue by rohit-nair** [idank/explainshell#227]
First off, @idank thanks for setting up this great resource and thanks to @anestv for the dark theme implementation.

One of the things I noticed while using dark theme is that when navigating to pages, we see flashing (shows up in light mode then switches to dark mode). This is happening as the logic to trigger dark mode happens client side on document.ready event.

Fix for this would be to do this server side while generating initial page response. For this the server needs to know about the user's theme setting. This can be achieved by setting it in the cookie when user selects dark mode for the first time and reading that cookie value for subsequent responses.

I've the changes working locally and will setup a PR for this.

Let me know your thoughts.

**Comment by idank** [comment]
Thanks for the pull request, looks good in general. I wonder if there's a client side way to prevent this though. Right now we're setting the theme at $(document).ready, is there an event that triggers before that we can use such that the flashing isn't visible?

**Comment by rohit-nair** [comment]
Perhaps the logic could be part of the initial page markup that gets sent and gets executed on parsing which would reduce the duration of flash a bit but won't completely remove it imo.

**Comment by idank** [comment]
Sadly I don't have time to look into other approaches myself. As long as you're confident that this is how others are solving this then I'm fine with taking it as is.

**Comment by rohit-nair** [comment]
Maybe @anestv or other contributors could pitch in. I'm ok with keeping the PR open for a bit.
