### ISSUE TITLE
Feature Request: being able to export an image of the page.

### ISSUE THREAD

**Issue by Duality4Y** [idank/explainshell#280]
It would be nice to have a way to export the explanation  some how either in image or maybe other formats.
my personal reason for this feature request is so that i can add an image of the explanation to documentation for example

**Comment by stoivo** [comment]
I suggest you just take a screenshot yourself.

**Comment by idank** [comment]
Agree with @stoivo, don't think this is worth it.

**Comment by Duality4Y** [comment]
alright
