### ISSUE TITLE
The cert for explainshell.com has expired

### ISSUE THREAD

**Issue by goalaleo** [idank/explainshell#283]
The cert expired today
![Screenshot 2021-08-10 at 16 03 13](https://user-images.githubusercontent.com/3275302/128871676-55ba3e53-5198-439e-98d6-21f06946fe75.png)

**Comment by idank** [comment]
Looks like the software that renews it requires a manual upgrade. 😩 Will get this resolved by the weekend.

**Comment by idank** [comment]
Fixed.
