### ISSUE TITLE
Expired certificate?

### ISSUE THREAD

**Issue by indigoblueraspberry** [idank/explainshell#287]
When visiting the website [https://www.explainshell.com](https://www.explainshell.com), now it displays that "explainshell.com certificate name does not match input" when inspecting the certificate.

**Comment by idank** [comment]
I'm not getting that here. Can you attach a screenshot?

**Comment by stoivo** [comment]
It seam like the certificate is only not for www.explainshell.com but only explainshell.com.
![Screenshot 2021-10-01 at 23 36 18](https://user-images.githubusercontent.com/3492040/135688825-986a12bc-f27c-437d-a58d-3c28bb9a91d2.png)

Also The 30th of oktober an old root lets encript key expired and the "new" root lets encript key is in OpenSSL 1.1.0 (over 4 years old). https://github.com/mperham/sidekiq/issues/5008
If you are running an old system that could also be an issue

**Comment by indigoblueraspberry** [comment]
Here is the certificate.

<img width="499" alt="cert" src="https://user-images.githubusercontent.com/44578534/135749508-477753ae-077e-4159-ba95-00301e0263d7.png">

**Comment by idank** [comment]
It's an old system with a recently updated certbot. The dns is configured with a cname entry from www.explainshell.com to explainshell.com. So I'm not what broke really :|.

**Comment by indigoblueraspberry** [comment]
According to my testing, now it works as expected. Thank you @idank!
