### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by bric3** [idank/explainshell#298]
I've seen this issue #1, mentioning contributing to https://github.com/idank/explainshell-manpages, but this repo last activity dates back to 2013.

This project has outstanding PRs.

Maybe it's time to move this project to an organization so multiple people can contribute?

**Comment by abitrolly** [comment]
@idank is missing since April, so it may be already too late.

**Comment by idank** [comment]
I'm still here! I don't think it matters whether it's in an organization or not. The way the service is currently built doesn't allow for easy contributions to the man pages db. I've long wanted to rewrite it to a wikipedia style model where it's all community driven but never got around to finishing that, nor did the any contributors stepped up to do it.

So to answer your question: yes the project is still alive, but it's pretty much in maintenance mode at the moment.

**Comment by abitrolly** [comment]
@idank that's nice to hear. )

Rewriting seems a big project on its own. I think that it is easier to people to contribute to rewriting if it is incremental process. So setting up a pinned issue with checklist that needs to be done for rewriting could bootstrap the process. And with Hacktoberfest it is easy to attract people to make contributions (not sure it is easy to review them though).

If you have time, it would be nice to get CI running https://github.com/idank/explainshell/pull/303 and then there are a couple of PRs that fix problems with running code from this repo on modern systems.

**Comment by idank** [comment]
Yes that would be nice to have, but it requires research and design, and getting into code that you wrote years ago and forgot all about. :) I'd love to do it one day though. I love that people are still interested and using the service, it's a great source of motivation to get into it again.
