### ISSUE TITLE
Wrong  numerical file permissions

### ISSUE THREAD

**Issue by MannyAdumbire** [idank/explainshell#311]
I tried **EXPLAIN** `install -g 0 -o 0 -m 0644 nuseradd.1 /usr/local/man/man8/`. The important bits show up fine, but the 0644 was mis-explained as **rwx**r-xr-x.
![explainshell-wrong-num-perms](https://user-images.githubusercontent.com/4621391/219821984-c872bb91-7f8c-4b1a-b0eb-25d0862b8dbc.jpg)
![bash-num-perms-wiki](https://user-images.githubusercontent.com/4621391/219821997-9e6eb696-aaa8-4d09-9975-b4491b17e7f3.jpg)

**Comment by 0x00cl** [comment]
Its not wrong in the sense that explainshell isn't trying to translate 0644 into letters permission. explainshell its taking that explanation from the man page of _install_

check `man install` you'll see that it says
```
       -m, --mode=MODE
              set permission mode (as in chmod), instead of rwxr-xr-x
```

Which is just showing that you can either use number or letters permission format.

**Comment by MannyAdumbire** [comment]
@0x00cl   Got it 😅
 Thanks for explaining.
