### ISSUE TITLE
Maybe add `git clone https://github.com/idank/explainshell.git` to the `Running explainshell locally` section. 

### ISSUE THREAD

**Issue by dmuiX** [idank/explainshell#321]
To me it wasn't clear from the beginning that I had to clone the repository before building. After I read the compose file it came to me. To clearyfi it maybe add `git clone https://github.com/idank/explainshell.git` to the `Running explainshell locally` Section.

**Comment by idank** [comment]
Good suggestion, can you send a PR?

**Comment by dmuiX** [comment]
Jip will do that.

**Comment by dmuiX** [comment]
Done 
https://github.com/idank/explainshell/pull/322
